NSERT INTO `Jogo` (`titulo_Jogo`, `descricao_Jogo`, `data_lancamento_Jogo`, `cod_desenvolvedor_fk`, `cod_publicadora_fk`) VALUES
-- Desenvolvedor IDs: 1:Naughty Dog, 2:Rockstar, 3:CDPR, 4:FromSoft, 5:Santa Monica, 6:Guerrilla, 7:Insomniac, 8:Nintendo, 9:BioWare, 10:Bethesda, 11:id Software, 12:Valve, 13:Remedy, 14:Larian, 15:Obsidian, 16:Respawn, 17:Sucker Punch, 18:Kojima, 19:Square Enix, 20:Capcom, 21:Riot, 22:Epic, 23:Mojang, 24:ConcernedApe
-- Publicadora IDs: 1:EA, 2:Ubisoft, 3:Nintendo, 4:Sony, 5:Activision, 6:Take-Two, 7:Square Enix, 8:Bandai Namco, 9:Capcom, 10:Sega, 11:Microsoft, 12:Tencent, 13:Konami, 14:Bethesda, 15:Warner Bros, 16:Devolver, 17:Annapurna, 18:CD Projekt, 19:FromSoftware, 20:Focus, 21:Paradox, 22:505, 23:Riot
('The Last of Us Part I', 'Um jogo de ação e aventura sobre sobrevivência em um mundo pós-apocalíptico.', '2022-09-02', 1, 4),
('Grand Theft Auto V', 'Um jogo de ação e aventura em mundo aberto na cidade de Los Santos.', '2013-09-17', 2, 6),
('The Witcher 3: Wild Hunt', 'Um RPG de mundo aberto onde você joga como Geralt de Rívia, um caçador de monstros.', '2015-05-19', 3, 18),
('Elden Ring', 'Um RPG de ação desafiador em um vasto mundo de fantasia sombria.', '2022-02-25', 4, 8),
('God of War Ragnarök', 'A continuação da jornada de Kratos e Atreus pelos reinos nórdicos.', '2022-11-09', 5, 4),
('Horizon Forbidden West', 'Aloy explora uma nova fronteira majestosa, mas perigosa, que esconde novas ameaças misteriosas.', '2022-02-18', 6, 4),
('Marvel''s Spider-Man 2', 'Peter Parker e Miles Morales enfrentam a derradeira prova de fogo para salvar a cidade de Venom e da ameaça do simbionte.', '2023-10-20', 7, 4),
('The Legend of Zelda: Tears of the Kingdom', 'Uma aventura épica pelas terras e céus de Hyrule em busca da Princesa Zelda.', '2023-05-12', 8, 3),
('Mass Effect Legendary Edition', 'A remasterização da aclamada trilogia de RPG de ficção científica.', '2021-05-14', 9, 1),
('The Elder Scrolls V: Skyrim', 'Um RPG de mundo aberto onde o jogador é o Dragonborn, um herói profetizado para derrotar dragões.', '2011-11-11', 10, 14),
('DOOM Eternal', 'Um jogo de tiro em primeira pessoa intenso e rápido, onde o jogador luta contra as forças do inferno.', '2020-03-20', 11, 14),
('Half-Life: Alyx', 'Uma experiência de realidade virtual no universo de Half-Life.', '2020-03-23', 12, 12),
('Control', 'Um jogo de ação e aventura em terceira pessoa com elementos sobrenaturais.', '2019-08-27', 13, 22),
('Baldur''s Gate 3', 'Um RPG baseado em Dungeons & Dragons com enorme liberdade e narrativa reativa.', '2023-08-03', 14, 14),
('Fallout: New Vegas', 'Um RPG pós-apocalíptico ambientado no deserto de Mojave.', '2010-10-19', 15, 14),
('Star Wars Jedi: Survivor', 'A continuação da história de Cal Kestis em sua luta contra o Império.', '2023-04-28', 16, 1),
('Ghost of Tsushima', 'Um samurai luta para proteger sua ilha durante a primeira invasão mongol no Japão.', '2020-07-17', 17, 4),
('Death Stranding', 'Um jogo de ação que desafia o gênero, onde o objetivo é reconectar uma sociedade fragmentada.', '2019-11-08', 18, 4),
('Final Fantasy VII Remake', 'A recriação do icônico RPG, expandindo a história de Midgar.', '2020-04-10', 19, 7),
('Resident Evil 4 (Remake)', 'A recriação do clássico de terror de sobrevivência com jogabilidade modernizada.', '2023-03-24', 20, 9),
('League of Legends', 'Um MOBA competitivo onde duas equipes de cinco campeões se enfrentam.', '2009-10-27', 21, 23),
('Fortnite', 'Um popular jogo de Battle Royale com mecânicas de construção.', '2017-07-25', 22, 22),
('Minecraft', 'Um jogo de sandbox onde os jogadores podem construir e explorar mundos infinitos.', '2011-11-18', 23, 11),
('Stardew Valley', 'Um RPG de simulação de fazenda onde o jogador herda uma propriedade rural.', '2016-02-26', 24, null),
('Red Dead Redemption 2', 'Uma história épica sobre honra e lealdade no final da era do Velho Oeste americano.', '2018-10-26', 2, 6),
('Sekiro: Shadows Die Twice', 'Um jogo de ação e aventura com foco em combate preciso e furtividade.', '2019-03-22', 4, 5),
('Bloodborne', 'Um RPG de ação sombrio e gótico, conhecido por sua alta dificuldade e atmosfera vitoriana.', '2015-03-24', 4, 4),
('Uncharted 4: A Thief''s End', 'A aventura final de Nathan Drake em busca de um tesouro pirata.', '2016-05-10', 1, 4),
('Super Mario Odyssey', 'Mario viaja por diversos reinos em sua nave, a Odyssey, para resgatar a Princesa Peach.', '2017-10-27', 8, 3),
('Cyberpunk 2077', 'Um RPG de ação e aventura em mundo aberto ambientado na megalópole de Night City.', '2020-12-10', 3, 18),
('Dark Souls III', 'O capítulo final da aclamada série de RPGs de ação, conhecido por seu combate desafiador.', '2016-03-24', 4, 8),
('God of War (2018)', 'Kratos, agora vivendo nas terras da mitologia nórdica, luta para sobreviver com seu filho Atreus.', '2018-04-20', 5, 4),
('Ratchet & Clank: Rift Apart', 'Uma aventura interdimensional com visuais impressionantes e jogabilidade de plataforma.', '2021-06-11', 7, 4),
('Alan Wake 2', 'Uma história de terror e sobrevivência com duas realidades jogáveis e uma narrativa densa.', '2023-10-27', 13, 22),
('Apex Legends', 'Um battle royale de heróis com jogabilidade rápida e baseada em esquadrões.', '2019-02-04', 16, 1),
('Titanfall 2', 'Um FPS aclamado por sua campanha single-player e jogabilidade ágil com robôs gigantes.', '2016-10-28', 16, 1),
('Hollow Knight', 'Um jogo de ação e aventura 2D em um vasto reino subterrâneo de insetos.', null, null),
('Celeste', 'Um jogo de plataforma desafiador com uma história emocionante sobre saúde mental.', null, null),
('Portal 2', 'Um jogo de puzzle em primeira pessoa com uma narrativa engenhosa e mecânicas de portais.', '2011-04-19', 12, 12),
('BioShock Infinite', 'Uma aventura em primeira pessoa na cidade flutuante de Columbia, com temas complexos.', null, 6),
('Metal Gear Solid V: The Phantom Pain', 'Um jogo de ação furtiva em mundo aberto com enorme liberdade tática.', '2015-09-01', 18, 13),
('The Legend of Zelda: Breath of the Wild', 'Uma aventura de mundo aberto que redefiniu a série Zelda.', '2017-03-03', 8, 3),
('Persona 5 Royal', 'Um RPG estiloso sobre um grupo de estudantes do ensino médio que se tornam ladrões de corações.', null, 10),
('Monster Hunter: World', 'Cace monstros gigantes em um ecossistema vivo e vibrante.', '2018-01-26', 20, 9),
('Street Fighter 6', 'A mais recente entrada na icônica série de jogos de luta, com novos modos e mecânicas.', '2023-06-02', 20, 9),
('Devil May Cry 5', 'Um jogo de ação hack and slash com combate estiloso e de alta octanagem.', '2019-03-08', 20, 9),
('Final Fantasy XVI', 'Uma épica fantasia sombria com combate em tempo real e batalhas de Eikons colossais.', '2023-06-22', 19, 7),
('Starfield', 'Um RPG de nova geração ambientado entre as estrelas, da Bethesda Game Studios.', '2023-09-06', 10, 11),
('Forza Horizon 5', 'Um jogo de corrida em mundo aberto ambientado em uma representação vibrante do México.', null, 11),
('Gears 5', 'Kait Diaz parte em uma jornada para descobrir a origem de sua família e a verdade por trás dos Locust.', null, 11),
('Hades', 'Um roguelike aclamado onde você joga como o príncipe do submundo tentando escapar do inferno.', null, null),
('Disco Elysium', 'Um RPG inovador sem combate, focado em diálogos e investigação.', null, null),
('Outer Wilds', 'Um mistério de exploração espacial sobre um sistema solar preso em um loop temporal infinito.', null, 17),
('Returnal', 'Um shooter em terceira pessoa roguelike com uma narrativa de ficção científica e terror psicológico.', null, 4),
('It Takes Two', 'Um jogo de aventura e plataforma exclusivamente cooperativo sobre um casal em crise.', null, 1),
('A Plague Tale: Requiem', 'A continuação da jornada de Amicia e seu irmão Hugo em uma França medieval devastada pela peste.', null, 20),
('Ori and the Will of the Wisps', 'Um belíssimo jogo de plataforma e aventura com uma história emocionante.', null, 11),
('Cuphead', 'Um jogo de ação e plataforma com um estilo de animação inspirado nos desenhos dos anos 1930.', null, null),
('The Binding of Isaac: Rebirth', 'Um roguelike de tiro com dois analógicos e temas sombrios.', null, null),
('Slay the Spire', 'Um construtor de baralhos roguelike onde você sobe uma torre enfrentando inimigos.', null, null),
('Among Us', 'Um jogo de dedução social multiplayer onde tripulantes tentam sobreviver a um impostor.', null, null),
('Fall Guys', 'Um jogo multiplayer de gincanas caóticas e divertidas.', '2020-08-04', null, 16),
('Genshin Impact', 'Um RPG de ação em mundo aberto com um vasto mundo para explorar e personagens elementais.', null, null),
('Valorant', 'Um jogo de tiro tático 5v5 baseado em personagens.', '2020-06-02', 21, 23),
('Overwatch 2', 'A sequência do popular shooter de heróis da Blizzard.', '2022-10-04', null, 5),
('Diablo IV', 'O retorno da aclamada série de RPG de ação, com um mundo sombrio e compartilhado.', '2023-06-05', null, 5),
('World of Warcraft', 'O MMORPG mais popular do mundo, com décadas de conteúdo e expansões.', null, 5),
('Call of Duty: Modern Warfare III (2023)', 'A mais recente iteração da popular franquia de FPS.', null, 5),
('Battlefield 2042', 'Um FPS multiplayer em larga escala com foco em guerra total.', null, 1),
('The Sims 4', 'Um jogo de simulação de vida onde você cria e controla pessoas.', null, 1),
('Assassin''s Creed Valhalla', 'Jogue como um guerreiro Viking em uma saga épica durante a Idade das Trevas da Inglaterra.', '2020-11-10', 2, 2),
('Far Cry 6', 'Lute para libertar a nação fictícia de Yara de um ditador implacável.', '2021-10-07', 2, 2),
('Rainbow Six Siege', 'Um shooter tático focado em combate de curta distância e destruição de cenários.', '2015-12-01', 2, 2),
('Watch Dogs: Legion', 'Recrute qualquer pessoa da cidade de Londres para formar uma resistência.', '2020-10-29', 2, 2),
('Cyberpunk 2077: Phantom Liberty', 'Uma expansão de suspense e espionagem para Cyberpunk 2077.', '2023-09-26', 3, 18),
('Hogwarts Legacy', 'Um RPG de ação e aventura em mundo aberto ambientado no universo de Harry Potter.', '2023-02-10', null, 15),
('Mortal Kombat 1', 'Um novo começo para a icônica franquia de luta, com um universo renascido.', '2023-09-19', null, 15),
('Batman: Arkham Knight', 'O capítulo final da série Arkham, onde Batman enfrenta a ameaça final em Gotham.', '2015-06-23', null, 15),
('Detroit: Become Human', 'Um jogo de aventura narrativa sobre androides que desenvolvem consciência.', null, 4),
('Heavy Rain', 'Um thriller interativo onde as escolhas do jogador moldam a busca por um serial killer.', null, 4),
('Until Dawn', 'Um jogo de terror interativo onde um grupo de amigos tenta sobreviver a uma noite em uma montanha.', null, 4),
('Lies of P', 'Um soulslike que reconta a história de Pinóquio em um mundo sombrio e cruel da Belle Époque.', null, null),
('Hi-Fi Rush', 'Um jogo de ação e ritmo onde o mundo se move com a música.', null, 11),
('Psychonauts 2', 'Uma aventura de plataforma que mergulha nas mentes de personagens excêntricos.', null, 11),
('Crusader Kings III', 'Um grande jogo de estratégia e simulação de dinastia medieval.', null, 21),
('Cities: Skylines II', 'O construtor de cidades mais realista já criado.', '2023-10-24', null, 21),
('Stellaris', 'Um jogo de grande estratégia de ficção científica sobre exploração e impérios espaciais.', '2016-05-09', null, 21),
('Arma 3', 'Um simulador de combate militar massivo em sandbox.', null, null),
('DayZ', 'Um jogo de sobrevivência hardcore em um mundo aberto pós-apocalíptico infestado de zumbis.', null, null),
('Rust', 'Um jogo de sobrevivência multiplayer onde o objetivo é sobreviver contra outros jogadores e o ambiente.', null, null),
('Terraria', 'Um jogo de aventura e sandbox 2D com elementos de exploração, construção e combate.', null, null),
('Valheim', 'Um jogo de sobrevivência e exploração brutal, inspirado na cultura viking.', null, null),
('Phasmophobia', 'Um jogo de terror psicológico cooperativo para 4 jogadores.', null, null),
('Sea of Thieves', 'Um jogo de aventura em mundo compartilhado que permite viver a vida de um pirata.', '2018-03-20', null, 11),
('No Man''s Sky', 'Um jogo de exploração espacial com um universo gerado proceduralmente.', '2016-08-09', null, null);